blueprint:
  name: Xiaomi MiJia wireless switch (WXKG01LM) Z2MQTT
  description: one, two ,three and four press commands
  domain: automation
  input:
    remote:
      name: Remote
      description: The action entity of your Styrbar remote
      selector:
        entity:
          domain: sensor
    onepress:
      name: one press
      description: Action to run on one press
      default: []
      selector:
        action: {}
    twopress:
      name: two presses
      description: Action to run on two presses
      default: []
      selector:
        action: {}
    threepress:
      name: three presses
      description: Action to run on three presses
      default: []
      selector:
        action: {}
    fourpress:
      name: four presses
      description: Action to run on four presses
      default: []
      selector:
        action: {}
      
  source_url: https://raw.githubusercontent.com/bvdberg01/Z2M-Styrbar-remote-blueprint/main/Z2M-IKEA-STYRBAR-remote.yaml
trigger:
  - platform: state
    entity_id: !input 'remote'
    attribute: action
condition: []
action:
  - variables:
      command: '{{ trigger.to_state.state }}'
  - choose:      
      - conditions:
          - '{{ command == ''single'' }}'
        sequence: !input 'onepress'
      - conditions:
          - '{{ command == ''double'' }}'
        sequence: !input 'twopress'    
      - conditions:
          - '{{ command == ''triple'' }}'
        sequence: !input 'threepress'
      - conditions:
          - '{{ command == ''quadruple'' }}'
        sequence: !input 'fourpress'
mode: parallel
max_exceeded: silent
